import type { Metadata } from 'next';
import { Mulish, Poppins } from 'next/font/google';
import '../assets/styles/globals.scss';
import { Providers } from '@/providers/Providers';
import { ToastContainer } from 'react-toastify';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	style: ['normal', 'italic'],
	variable: '--font-poppins',
	display: 'swap',
});
const mulish = Mulish({
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '700'],
	variable: '--font-mulish',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${poppins.variable} ${mulish.variable}`}>
			<body className="normal scrolbar-hidden">
				<ToastContainer position="top-center" theme="colored" />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
