import { ICourseCard } from "@/components/ui/cards/course-card/CourseCard";

export const courses: ICourseCard[] = [
  {
    images: ["/uploads/images/business.jpg"],
    rating: "4.5 (120)",
    views: "28,500",
    lessons: 3,
    slug: "",
    title: "Everything You Need to Know About Business",
    teacher: "Nicole Brown",
    price: 99.99,
    sale: 49.65,
    teacherAvatar: "https://i.pravatar.cc/40?img=19",
  },
  {
    images: ["/uploads/images/choose.jpg"],
    rating: "4.5 (120)",
    views: "28,500",
    lessons: 3,
    slug: "",
    title: "Statistics Data Science and Business Analysis",
    teacher: "Nicole Brown",
    price: 99.99,
    sale: 49.65,
    teacherAvatar: "https://i.pravatar.cc/40?img=19",
  },
  {
    images: ["/uploads/images/course.jpg"],
    rating: "4.5 (120)",
    views: "28,500",
    lessons: 3,
    slug: "",
    title: "AWS Certified Solutions Architect Associate",
    teacher: "Nicole Brown",
    price: 99.99,
    sale: 49.65,
    teacherAvatar: "https://i.pravatar.cc/40?img=19",
  },
  {
    images: ["/uploads/images/course-2.jpg"],
    rating: "4.5 (120)",
    views: "28,500",
    lessons: 3,
    slug: "",
    title: "Web UI design best practises",
    teacher: "Nicole Brown",
    price: 99.99,
    sale: 49.65,
    teacherAvatar: "https://i.pravatar.cc/40?img=19",
  },

  {
    images: ["/uploads/images/course-1.jpg"],
    rating: "4.5 (120)",
    views: "28,500",
    lessons: 3,
    slug: "",
    title: "AWS Certified Solutions Architect",
    teacher: "Nicole Brown",
    price: 99.99,
    sale: 49.65,
    teacherAvatar: "https://i.pravatar.cc/40?img=19",
  },

  {
    images: ["/uploads/images/uiux.jpg"],
    rating: "4.5 (120)",
    views: "28,500",
    lessons: 3,
    slug: "learn-adobe-xd-prototyping",
    title: "UIUX Design Conference Meeting",
    teacher: "Nicole Brown",
    price: 99.99,
    sale: 49.65,
    teacherAvatar: "https://i.pravatar.cc/40?img=19",
  },
];
